"""Low-level PDF outline helpers using pypdf."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from pypdf import PdfReader, PdfWriter
from pypdf.generic import Destination, NameObject


@dataclass(frozen=True, slots=True)
class PdfOutlineItem:
    title: str
    page_index: int


def extract_outline_items(pdf_path: str | Path) -> list[PdfOutlineItem]:
    """Return valid native outline destinations from *pdf_path*, flattened."""
    reader = PdfReader(Path(pdf_path))
    items: list[PdfOutlineItem] = []

    def visit(nodes: list[object]) -> None:
        for node in nodes:
            if isinstance(node, list):
                visit(node)
                continue
            if not isinstance(node, Destination):
                continue
            page_index = reader.get_destination_page_number(node)
            title = str(node.title).strip()
            if title and page_index is not None and page_index >= 0:
                items.append(PdfOutlineItem(title, page_index))

    visit(reader.outline)
    return items


def add_outline_items(
    pdf_path: str | Path,
    items: Iterable[PdfOutlineItem],
) -> None:
    """Replace the PDF outline with *items*, replacing the file in-place."""
    path = Path(pdf_path)
    reader = PdfReader(path)
    page_count = len(reader.pages)

    writer = PdfWriter()
    writer.clone_document_from_reader(reader)
    writer.root_object.pop(NameObject("/Outlines"), None)

    for item in items:
        if not item.title.strip():
            continue
        if item.page_index < 0 or item.page_index >= page_count:
            continue
        writer.add_outline_item(item.title, item.page_index)

    tmp = path.with_suffix(".tmp_outline.pdf")
    replaced = False
    try:
        with tmp.open("wb") as fh:
            writer.write(fh)
        tmp.replace(path)
        replaced = True
    finally:
        if not replaced:
            tmp.unlink(missing_ok=True)


def technical_fallback_items(
    block_size: int,
    total_pages: int,
) -> list[PdfOutlineItem]:
    """Return clearly labelled page-range entries for technical fallback."""
    if block_size < 1:
        raise ValueError("block_size deve essere almeno 1.")
    if total_pages < 0:
        raise ValueError("total_pages non può essere negativo.")

    return [
        PdfOutlineItem(
            f"Fallback tecnico - Pagine {zero_start + 1}–{zero_end}",
            zero_start,
        )
        for zero_start in range(0, total_pages, block_size)
        for zero_end in [min(zero_start + block_size, total_pages)]
    ]


def add_technical_fallback_bookmarks(
    pdf_path: str | Path,
    block_size: int,
    total_pages: int | None = None,
) -> None:
    """Add reliable page-range bookmarks to *pdf_path*.

    For v0.1.0 this is the only outline generated by the application.
    """
    if block_size < 1:
        raise ValueError("block_size deve essere almeno 1.")

    path = Path(pdf_path)
    reader = PdfReader(path)
    page_count = len(reader.pages)
    n_pages = min(total_pages, page_count) if total_pages is not None else page_count
    add_outline_items(path, technical_fallback_items(block_size, n_pages))
